feat/rooms Join/Leave Room Endpoint
acmutd/bsg pull request #23
Opened 2023-11-13 05:14 UTC by Anphs

POST Join Room Endpoint
POST Leave Room Endpoint
Room Leader Mechanism

2023-11-13 17:49 UTC, DedsecKnight requested changes

2023-11-13 17:49 UTC, DedsecKnight commented on central-service/services/room.go
> +		room.Admin = result
I think you would need to save the room update here. Look into [this guide](https://gorm.io/docs/update.html) for more details.

2023-11-13 17:49 UTC, DedsecKnight commented on central-service/services/room.go
> +	return room, nil
Any reason why we need to return a Room object here?

2023-11-13 17:49 UTC, DedsecKnight commented on central-service/services/room.go
> +	return room, nil
Any reason why we need to return a Room object here?

2023-11-13 17:49 UTC, DedsecKnight commented on central-service/services/room.go
> +	// add check to make sure they're not in other rooms?
Probably reasonable to assume that we allow a person to be in multiple rooms at the same time

2023-11-14 03:11 UTC, Anphs commented on central-service/services/room.go
> +	return room, nil
The Room object contains the room name if we want to display it in the UI along with the current admin id if we want to color their chat messages

2023-11-14 03:11 UTC, Anphs commented on central-service/services/room.go
> +	return room, nil
Changed it to return error or nil

2023-11-15 03:58 UTC, 1solomonwakhungu approved these changes
Looks good.

Will need to setup a meeting to discuss communication between RTC and Central Service.

2023-11-15 22:01 UTC, DedsecKnight approved these changes
lgtm!

2023-11-15 22:29 UTC, merged