Kafka-queue
acmutd/bsg pull request #32
Opened 2024-01-10 13:22 UTC by minhhuy24072002

2024-01-10 13:23 UTC, minhhuy24072002 commented
To run the test please bring up to docker-compose using `docker compose up` command

2024-02-01 16:49 UTC, DedsecKnight approved these changes
lgtm! nicely done :+1:

2024-02-05 21:54 UTC, 1solomonwakhungu requested changes

2024-02-05 21:54 UTC, 1solomonwakhungu commented on kafka-queue/kafka_util.go
> +		panic(err)
Panicking in code will stop the program. 
In production, this service will stop working is there is an error.
Best to print the error and return.

2024-02-05 21:54 UTC, 1solomonwakhungu commented on kafka-queue/kafka_util.go
> +		panic(errors.New("Unable to create kafka consumer due to error " + initConsumerErr.Error()))
Another panic here.

2024-02-11 23:28 UTC, 1solomonwakhungu approved these changes
:

2024-02-11 23:28 UTC, merged