Implemented User Service and Authentication
acmutd/bsg pull request #5
Opened 2023-10-04 00:20 UTC by DedsecKnight

- Remaining task for this PR: 

- [ ] Add unit test
- [ ] Add documentation
- [ ] Figure out a better way to handle case in which user do not exist

2023-10-11 04:35 UTC, 1solomonwakhungu commented on docker-compose.yml
> +      POSTGRES_PASSWORD: bsgdev
Will need to find a way to access the password securely.

One idea is to store the files in a Google Secrets Manager and have a script pull the secret values from the manager into a .env file. The docker will then read the secret values from the .env file.

2023-10-11 04:42 UTC, 1solomonwakhungu commented on central-service/main.go
> +	dsn := "host=db user=bsgdev password=bsgdev dbname=bsg port=5432 sslmode=disable Timezone=America/Chicago"
Will need to find a way to secure this information.

We can use the Google Secrets Manger package to pull this sensitive information.

2023-10-11 05:12 UTC, 1solomonwakhungu requested changes

2023-10-11 05:12 UTC, 1solomonwakhungu commented on central-service/main.go
> +		fmt.Println("Error connecting to the database")
Printing out the err variable is good practice since it will help during the debugging phase if this error occurs.

`fmt.Println("Error connecting to the database", err)`

2023-10-11 05:12 UTC, 1solomonwakhungu commented on central-service/main.go
> +		fmt.Println("Error migrating User schema")
Same here

2023-10-11 05:12 UTC, 1solomonwakhungu commented on central-service/services/user.go
> +		log.Fatalf("error initializing app: %v\n", err)
Logging Fatal is not recommended since that will quit the application.

2023-10-11 05:12 UTC, 1solomonwakhungu commented on central-service/services/user.go
> +	result := service.db.Where("ID = ?", userID).First(&user)
Change to `service.db.Where("ID = ?", userID).Limit(1).Find(&user)`

This would eliminate the extra check for `ErrRecordNotFound`

https://gorm.io/docs/query.html

2023-10-12 06:22 UTC, 1solomonwakhungu approved these changes
ship it!

2023-10-15 05:04 UTC, spierceVR approved these changes
Mike nailed it with the code and Solomon W nailed it with his comments! 

Going ahead and approving though in case you wanna skip the DI style suggestion

2023-10-15 05:04 UTC, spierceVR commented on central-service/controllers/user.go
> +func (controller *UserController) UpdateUserDataEnpoint(c echo.Context) error {
```suggestion
func (controller *UserController) UpdateUserDataEndpoint(c echo.Context) error {
```
fix typo

2023-10-15 05:04 UTC, spierceVR commented on central-service/controllers/user.go
> +	g.PUT("/", controller.UpdateUserDataEnpoint)
```suggestion
	g.PUT("/", controller.UpdateUserDataEndpoint)
```
related typo

2023-10-15 05:04 UTC, spierceVR commented on central-service/main.go
> +	userController.SetUserService(&userService)
```suggestion
	userService := services.InitializeUserService(db)
	userController := controllers.InitializeUserController(&userService)
```

This is a total nitpick but maybe constructor injection makes it a bit more explicit that userService is a required dependency for the userController?

2023-10-15 05:18 UTC, merged